FROM node:24.4 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
COPY prisma ./prisma/

RUN yarn install --frozen-lockfile

COPY . .

ENV DISABLE_ERD=true
RUN npx prisma generate && yarn build

EXPOSE 3000

CMD ["sh", "-c", "yarn container:db:deploy && yarn start:dev"]